### ISSUE TITLE
Detect and handle terminals without wide and combining character support

### ISSUE THREAD

**Issue by wardi** [urwid/urwid#48] opened 2013-12-30 15:15 UTC
Many terminals have poor UTF-8 handling that causes the screen text to be skewed when UTF-8 combining characters or wide characters are used.

**Comment by tonycpsu** [comment] 2019-04-05 22:13
@wardi: this seems like a duplicate of https://github.com/urwid/urwid/issues/225, no?

**Closed** 2020-06-13 03:51 UTC
Labels: feature
