### ISSUE TITLE
[BUG] 2.4.2 introduced regression (or maybe the original code was wrong all along)

### ISSUE THREAD

**Issue by prometheanfire** [urwid/urwid#838] opened 2024-02-23 16:26 UTC
##### Description:
When popping up a 'floating' dialog box for reviewing a commit the software exits/backtraces.

```
  Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/gertty", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/gertty/app.py", line 943, in main
    g.run()
  File "/usr/lib/python3.11/site-packages/gertty/app.py", line 362, in run
    self.loop.run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 339, in run
    self._run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 441, in _run
    self.event_loop.run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/select_loop.py", line 182, in run
    self._loop()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/select_loop.py", line 218, in _loop
    self._entering_idle()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/select_loop.py", line 171, in _entering_idle
    callback()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 648, in entering_idle
    self.draw_screen()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 665, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/frame.py", line 594, in render
    body = self.body.render((maxcol, maxrow - ftrim - htrim), focus and self.focus_part == "body")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/overlay.py", line 568, in render
    top_c = self.top_w.render(self.top_w_size(size, left, right, top, bottom), focus)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 780, in render
    canv = get_delegate(self).render(size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 780, in render
    canv = get_delegate(self).render(size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/pile.py", line 794, in render
    canv = w.render(w_size, focus=focus and item_focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/columns.py", line 903, in render
    w.render(w_size, focus=focus and self.focus_position == i),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/filler.py", line 205, in render
    canv = self._original_widget.render((maxcol,), focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/pile.py", line 787, in render
    _widths, heights, size_args = self.get_rows_sizes(size, focus)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/pile.py", line 698, in get_rows_sizes
    heights.append(w.pack(w_h_arg, item_focus)[1])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/columns.py", line 875, in pack
    return super().pack(size, focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 519, in pack
    raise WidgetError(f"Cannot pack (maxcol,) size, this is not a flow widget: {self!r}")
urwid.widget.widget.WidgetError: Cannot pack (maxcol,) size, this is not a flow widget: <Columns selectable fixed widget>
```

##### Affected versions (if applicable)
- [x] `2.6.5` (latest from pypi)
- [x] `2.4.2` (introduced here)

##### Steps to reproduce (if applicable)
open the software (gertty), open a code review, press `r` to open the review process, witness crash

##### Expected/actual outcome
no crash

**Comment by penguinolog** [comment] 2024-02-26 09:30
Looks like `gertty` is a hard pain.
I found my old creds for opendev, installed development version (since last release was 5 years ago)...
First it crashed on SQLAlchemy 2 (while patch for support was merged few weeks ago: https://review.opendev.org/c/ttygroup/gertty/+/880123)
After downgrade of SQLAlchemy I ended with `BrokenPipeError` on `sync` on app start, but TUI was shown. (
On keypress I received `ColumnsWarning` that columns for TUI is used incorrectly (I can try to fix it in project) and 6 SQLAlchemy warnings...
Traceback for this issue was not reached, because no any CR was loaded.

**Comment by prometheanfire** [comment] 2024-02-26 16:30
Thanks for taking a deeper look at things.  I actually did the workaround in gertty, it's basically been semi-abandoned for a while now.  I don't expect you (or other urwid devs) to fix another projects problems but any help you are willing to give will definitely be appreciated.

**Comment by penguinolog** [comment] 2024-02-26 16:36
Please re-check this issue with the last urwid version: it maybe fixed by fixing "empty pile" / "empty columns" sizing calculation.

P.S. project looks almost dead, but technically can be reanimated since it's OpenStack managed. Btw when I open Gerrit - I seen "git-review" change request, which got a lot of +1 (and one from me) >8 years ago and not merged:-(. OpenStack is not easy

**Comment by prometheanfire** [comment] 2024-02-26 18:35
looks like it's still occuring with 2.6.5

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/gertty", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/gertty/app.py", line 943, in main
    g.run()
  File "/usr/lib/python3.11/site-packages/gertty/app.py", line 362, in run
    self.loop.run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 342, in run
    self._run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 444, in _run
    self.event_loop.run()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/select_loop.py", line 182, in run
    self._loop()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/select_loop.py", line 218, in _loop
    self._entering_idle()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/select_loop.py", line 171, in _entering_idle
    callback()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 655, in entering_idle
    self.draw_screen()
  File "/usr/lib/python3.11/site-packages/urwid/event_loop/main_loop.py", line 672, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/frame.py", line 464, in render
    body = self.body.render((maxcol, maxrow - ftrim - htrim), focus and self.focus_part == "body")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/overlay.py", line 818, in render
    top_c = self.top_w.render(self.top_w_size(real_size, left, right, top, bottom), focus)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 711, in render
    canv = get_delegate(self).render(size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 711, in render
    canv = get_delegate(self).render(size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/pile.py", line 842, in render
    canv = w.render(w_size, focus=focus and item_focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/columns.py", line 978, in render
    w.render(w_size, focus=focus and self.focus_position == i),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/filler.py", line 243, in render
    canv = self._original_widget.render((maxcol,), focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 112, in cached_render
    canv = fn(self, size, focus=focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/pile.py", line 835, in render
    _widths, heights, size_args = self.get_rows_sizes(size, focus)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/pile.py", line 743, in get_rows_sizes
    heights.append(w.pack(w_h_arg, item_focus)[1])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/columns.py", line 950, in pack
    return super().pack(size, focus)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urwid/widget/widget.py", line 401, in pack
    raise WidgetError(f"Cannot pack (maxcol,) size, this is not a flow widget: {self!r}")
urwid.widget.widget.WidgetError: Cannot pack (maxcol,) size, this is not a flow widget: <Columns selectable fixed widget with 2 items>
```

**Comment by penguinolog** [comment] 2024-02-26 19:33
Looks like I're reach reproduce possibility.
And the worst part is: sizing is expected to be `FLOW`, but it was not declared and can be rendered as `FIXED`, but in code present explicit expand of `size` argument (even if it's not used at all)

**Comment by penguinolog** [comment] 2024-02-26 19:52
IMHO, better to fix here: https://review.opendev.org/c/ttygroup/gertty/+/910265

(I can make extra "try-except-warn" construction, but explicit API usage should explicit declare it's requirements)

**Comment by prometheanfire** [comment] 2024-02-26 21:30
I tried it, I think it did fix some other issues, but not the one at issue.
https://gist.github.com/prometheanfire/9c6be17be0f6118740198f86b8d238a2

**Comment by penguinolog** [comment] 2024-02-27 07:29
Last traceback says, that `Columns` is FIXED-only. This should happen only if all contents fixed-only. Looks weird.
We have specific logic to mark BOX-only (in case of BOX-only widgets in columns without "box_columns" mark), but in case of any FLOW widget in contents, `Columns` should support FLOW even if GIVEN width used.

**Comment by penguinolog** [comment] 2024-02-27 17:09
Final reason found.
Fix in 2 directions (downstream: https://review.opendev.org/c/ttygroup/gertty/+/910358)

**Closed** 2024-02-27 18:13 UTC
Labels: bug, Widget

**Comment by prometheanfire** [comment] 2024-02-27 19:45
thanks for the work here, confirmed it worked in the gerrit review
