### ISSUE TITLE
Trouble focusing widgets in a GridFlow

### ISSUE THREAD

**Issue by bk2204** [urwid/urwid#61] opened 2014-03-23 23:10 UTC
When I create a GridFlow where most of the items are Piles containing a Text and an Edit, but some are just empty Piles, I'm unable to focus a filled Pile when it is alone on a row.

If you run the grid.py file from https://gist.github.com/bk2204/9731198 in a terminal, you will be unable to select the Edit for Cell 4 with the mouse or the cursor keys. Hitting the down key from Cell 2 takes you directly to Cell 6.

I believe this did work in earlier versions.

**Comment by penguinolog** [comment] 2024-01-17 16:24
I reproduced this issue:

```python
>>> import urwid
>>> a = urwid.Button(u"Button A")
>>> b = urwid.Button(u"Button B")
>>> c = urwid.Text(u"Text C")
>>> d = urwid.Button(u"Button D")
>>> grid = urwid.GridFlow([a,b,c,d], cell_width=36, h_sep=2, v_sep=1, align='left')
>>> fill = urwid.Filler(grid, 'top')
>>> fill
<Filler selectable box/flow widget <GridFlow selectable fixed/flow widget> valign=<VAlign.TOP: 'top'>>
>>> fill.original_widget
<GridFlow selectable fixed/flow widget>
>>> fill.original_widget.focus
<Button selectable fixed/flow widget 'Button A'>
>>> fill.keypress((80, 24), "right")
>>> fill.original_widget.focus
<Button selectable fixed/flow widget 'Button B'>
>>> fill.keypress((80, 24), "right")
'right'
>>> fill.original_widget.focus
<Button selectable fixed/flow widget 'Button B'>
```

**Comment by penguinolog** [comment] 2024-01-17 16:32
After detail checking and adjusting size to fit in 1 row, everything went smooth.
For original size, GridFlow form buttons in 2 rows, so "right" button was correctly ignored. Using "down" instead moved focus to the "Button D". Since on the left side from it is not selectable widget, "left" will not move focus without changing row.

Not a bug, closing

**Closed by penguinolog** 2024-01-17 16:32 UTC
