### ISSUE TITLE
offere mail-adress to google-groups

### ISSUE THREAD

**Issue by buhtz** [urwid/urwid#181] opened 2016-03-23 10:49 UTC
Your link to the google-groups is quite complex
https://groups.google.com/a/excess.org/d/forum/urwid

I tried some combinations but this doesn't work.

Normaly I it is very easy to create mail-adress out of it.
e.g. https://groups.google.com/group/sqlalchemy becomes sqlalchemy@googlegroups.com with the corrosponding sqlalchemy+unsubscribe@googlegroups.com and sqlalchemy+subscribe@googlegroups.com

**Comment by wardi** [comment] 2016-03-23 12:58
closing as duplicate of #180

**Closed by wardi** 2016-03-23 12:58 UTC
